// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNb26CJEK7RdRwO4XcjcWpc8BdUmIHZy0',
    appId: '1:293102619869:web:597ffc591831dbe0f1df34',
    messagingSenderId: '293102619869',
    projectId: 'flutter-chat-app-40e68',
    authDomain: 'flutter-chat-app-40e68.firebaseapp.com',
    storageBucket: 'flutter-chat-app-40e68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkAvazAvkL0opqvyQekbzprJvvp5QEpI',
    appId: '1:293102619869:android:98bd83a9e34b7a15f1df34',
    messagingSenderId: '293102619869',
    projectId: 'flutter-chat-app-40e68',
    storageBucket: 'flutter-chat-app-40e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySCn0M4qPf9Zv7BZV49zzIt40IIKkuNc',
    appId: '1:293102619869:ios:86f5baa89e78f9dcf1df34',
    messagingSenderId: '293102619869',
    projectId: 'flutter-chat-app-40e68',
    storageBucket: 'flutter-chat-app-40e68.appspot.com',
    iosClientId: '293102619869-ho63ls3704p3hfjk68p5dlvtuh6vull3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
